### PR TITLE
Chore: drop Node v < 10 | Move from ava to jest

### PR DESCRIPTION
**Pull request by JPeer264**
(ref: https://github.com/appveyor/ci/issues/2921#issuecomment-501016533)

### CODE REVIEW

**Comment by JPeer264** [comment]
We should drop Node v4 and v6 and support only Node v10 and v12. Then appveyor should go green

**Comment by aichbauer** [comment]
That sounds right. Don't forget to change the node versions for the travis build as well.

**Comment by JPeer264** [comment]
@aichbauer appveyor works now with jest, but the coverage is just more strict than before (imports are not included in the coverage), that's why coveralls is now dropping 2.5%

**Comment by aichbauer** [comment]
No problem. 

Send from GitHub Android App 😱

**Pull request merged**
